### PR TITLE
Chef 16 Fixes

### PR DESCRIPTION
**Pull request by zimmerry**

### CODE REVIEW

**Comment by zimmerry** [comment]
[Chef 16: osl-scponly](https://trello.com/c/IrnlJsbN/1990-chef-16-osl-scponly)

**Review by ramereth — APPROVED** [review]
Please do a minor bump.

**Comment by zimmerry** [comment]
!bump minor *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v1.2.0.  Have a nice day!

**Pull request merged**
